image: Visual Studio 2022

version: '1.1.{build}'

install:
    - cmd: git submodule update --init --recursive

before_build:
  - cmake -G "Visual Studio 17 2022" -A x64 -B Build -S . -DVERSION=%APPVEYOR_BUILD_VERSION%
  # Run clang-format
  - ps: |
      $env:PATH="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages\;$env:PATH"
      clang-format --version
      powershell ./format-source.ps1
      git diff --exit-code Source
      if ($lastexitcode -gt 0) {
        Add-AppveyorMessage -Category Error -Message "Source code not formatted correctly"
        exit 1
      }

configuration:
  - RelWithDebInfo

build:
  project: Build/MStarPlayer.sln

after_build:
   - 7z a MStarPlayer.zip ./Build/MStarPlayer_artefacts/RelWithDebInfo/MStarPlayer.exe
   - 7z a MStarPlayer_PDB.zip ./Build/MStarPlayer_artefacts/RelWithDebInfo/MStarPlayer.pdb
   - choco pack --version %APPVEYOR_BUILD_VERSION%

artifacts:
  - path: MStarPlayer.zip
  - path: MStarPlayer_PDB.zip

deploy:
  provider: FTP
  protocol: ftps
  host:
    secure: nxZhnnxRwiBnT7WN+Yxt8IEKkOXwDkjGDb1mRWvrMZs=
  username:
    secure: HaHMzcvkYVKEK9MnfexXjA==
  password:
    secure: yYUQDY9IKwXXXIFJXYtaOA==
  on:
    branch: master

